binance:
  api_key: "YOUR_BINANCE_API_KEY"
  api_secret: "YOUR_BINANCE_SECRET"

trade:
  symbol: "BTCETH"
  trade_amount: 0.001
  confidence_threshold: 0.75
  interval: "15m"

trade:
  symbol: "BTCUSDT"
  quantity: 0.001
  confidence_threshold: 0.75
  interval: "15m"

model:
  target_shift: 3
  feature_columns:
    - rsi
    - ema_10
    - macd
